### ISSUE TITLE
how to make a custom widget collaborative

### ISSUE THREAD

**Issue by seshubonam** [nordeck/matrix-neoboard#154]
I am using a url for an inage editor and would like this to be collaborative. is there a matrix documentation on how to make a cystom widget collaborative with users inside that room. 

or how we can adapt this repo to a custom url.

**Comment by maheichyk** [comment]
This doesn't seem like a NeoBoard issue, but more like general widget development/collaboration questions that could be asked in the development channels of libs/specs that will be used.
