### ISSUE TITLE
Demo site isn't working

### ISSUE THREAD

**Issue by roland-5** [nordeck/matrix-neoboard#171]
If I try open https://nordeck.github.io/matrix-neoboard/ it shows me this:
```
Only runs as a widget

You need to register this URL as a widget, it's not possible to use it standalone. Run this command in the matrix room you want to register the widget in:

/addwidget https://nordeck.github.io/matrix-neoboard/
```

**Comment by maheichyk** [comment]
The widget cannot be used as a standalone, it has to be added to the matrix room in order to be used. The easiest is to use the command mentioned `/addwidget https://nordeck.github.io/matrix-neoboard/` and insert it into a message box of the Element client.
