### ISSUE TITLE
Widget crash when opening a NeoBoard for the first time

### ISSUE THREAD

**Issue by jaller94** [nordeck/matrix-neoboard#335]
**Describe the bug**

**Steps To Reproduce**

0. I use Element Web on Firefox 122.
1. Got an invitation to a room with a NeoBoard. (!pQsOZaCCFWWaVfIknH:nordeck.io)
2. Opened NeoBoard via the toggle icon in the room header.

**Expected behavior**
NeoBoard opens without any issues.

**Screenshots / Videos**

```
NS@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:1136917
DG@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:1681454
ua@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:553097
qa@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:562664
Gu@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:606388
Is@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:592640
Os@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:592568
_s@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:592429
bs@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:589395
534/Yo/<@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:538889
3095/t.unstable_runWithPriority@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:649827
Ho@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:538666
Yo@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:538836
Ko@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:538769
hs@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:586772
Aa@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:558424
na/l</<@https://neoboard.widget.nordeck.io/static/js/main.58356e60.js:2:797932
```

JavaScript: Console export: 
[console-export-2024-2-15_18-1-9.txt](https://github.com/nordeck/matrix-neoboard/files/14295172/console-export-2024-2-15_18-1-9.txt)

**Environment:**
 - OS: Manjaro Linux, based on the Arch Linux btw
 - Browser: Firefox 122.0

**Additional context**

- On the second try of opening this widget, it loaded without an issue.
- Sadly, I don't have a non-minimized version of the error's trace stack.
- If the JS-Console output doesn't help, just close the ticket, I guess. :shrug:

**Comment by maheichyk** [comment]
@jaller94 thanks for the issue. It will be resolved by the linked PR: in this case user will be asked to wait for "moderator" that will initialize the room and the whiteboard properly.
