### ISSUE TITLE
Broken GitHub Page

### ISSUE THREAD

**Issue by jaller94** [nordeck/matrix-neoboard#424]
**Describe the bug**

The GitHub Page https://nordeck.github.io/matrix-neoboard/ is just white.

**Steps To Reproduce**

1. Go to https://nordeck.github.io/matrix-neoboard/

**Expected behavior**

* Instructions to install this widget via Element Web.
* Or an error message that scripts couldn't be loaded.

**Screenshots / Videos**

![Screenshot_2024-05-08_15-04-51](https://github.com/nordeck/matrix-neoboard/assets/10872136/a657aff6-4eac-498d-9731-31955d7b5212)

**Comment by maheichyk** [comment]
@jaller94 neoboard is deployed to Gthub Page again now, thanks for the issue found.
